// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANzZCPA1nFo9Xj7npLYQYGSjRhC-vBqZg',
    appId: '1:845611483894:web:d7609a6a152d5061c5e2d7',
    messagingSenderId: '845611483894',
    projectId: 'zoomclone-47286',
    authDomain: 'zoomclone-47286.firebaseapp.com',
    storageBucket: 'zoomclone-47286.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-nZqo_NDGlhoQP1lmz8Vu8NYWxUNGmnc',
    appId: '1:845611483894:android:5e874f459a6fceeec5e2d7',
    messagingSenderId: '845611483894',
    projectId: 'zoomclone-47286',
    storageBucket: 'zoomclone-47286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDViHzE42g7r8m2-EtJa707bDKVIfwrH-E',
    appId: '1:845611483894:ios:fd295f1cdfa591dcc5e2d7',
    messagingSenderId: '845611483894',
    projectId: 'zoomclone-47286',
    storageBucket: 'zoomclone-47286.appspot.com',
    iosClientId: '845611483894-mtpsc8bjcr4u5p0tdpv9547agb6mrl0t.apps.googleusercontent.com',
    iosBundleId: 'com.zoomclone.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDViHzE42g7r8m2-EtJa707bDKVIfwrH-E',
    appId: '1:845611483894:ios:fd295f1cdfa591dcc5e2d7',
    messagingSenderId: '845611483894',
    projectId: 'zoomclone-47286',
    storageBucket: 'zoomclone-47286.appspot.com',
    iosClientId: '845611483894-mtpsc8bjcr4u5p0tdpv9547agb6mrl0t.apps.googleusercontent.com',
    iosBundleId: 'com.zoomclone.zoomClone',
  );
}
